// Generated by https://quicktype.io
import { QuickPick } from '@/types/QuickPick';
import { JackpotSize } from '@/types/JackpotSize';

export interface LotteryTeasers {
    id: string;
    drawDate: string;
    closingDate: string;
    comingSoon: boolean;
    jackpotSize: JackpotSize;
    jackpotType: string;
    lotteryType: string;
    quickPick: QuickPick;
    __typename: string;
}
